on:
  pull_request:
    branches:
    - main
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'enhancement')
    steps:
    - run: |
        echo "enhancement PR was merged"
