on:
  pull_request:
    branches:
    - main
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    # This can error if there are braces in the JSON !!!
    - run: |
        echo "${{ toJSON(github.event) }}"
    - run: |
        echo "${{ toJSON(github.event.pull_request) }}"
      if: contains(github.event.pull_request.labels.*.name, 'enhancement')
      name: Runs if enhancement label is present
