on: 
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        type: choice
        required: true
        options:
        - major
        - minor
        - patch
        - premajor
        - preminor
        - prepatch
        - prerelease
        default: patch
      prerelease-identifier:
        description: 'Pre-release identifier (only for pre-release builds)'
        required: false

name: 'Prepare release PR'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Update changelog
      id: update-changelog
      uses: release-flow/keep-a-changelog-release@main
      with:
        release-type: ${{ github.event.inputs.release-type }}
        changelog: does-not-exist
    - run: |
        echo "New release version: ${{ steps.update-changelog.outputs.new-release-version }}"
        cat CHANGELOG.md