on: 
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        type: choice
        required: true
        options:
        - major
        - minor
        - patch
        - premajor
        - preminor
        - prepatch
        - prerelease
        default: patch
      prerelease-identifier:
        description: 'Pre-release identifier (only for pre-release builds)'
        required: false

name: 'Prepare release PR'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Update changelog
      id: update-changelog
      uses: release-flow/keep-a-changelog-release@main
      with:
        release-type: ${{ github.event.inputs.release-type }}
    - run: |
        echo "New release version: ${{ steps.update-changelog.outputs.new-release-version }}"
        cat CHANGELOG.md
    - name: 'Ensure autorelease label exists'
      run: |
        LABEL=$(gh api repos/$GITHUB_REPOSITORY/labels --jq '.[] | select(.name=="autorelease")')
        if [[ -z "$LABEL" ]]; then
          echo "Creating 'autorelease' label"
          gh api --silent repos/$GITHUB_REPOSITORY/labels -f name="autorelease" -f color="baa938" -f description="This is an automatically-created PR to trigger a release"
        else
          echo "'autorelease' label exists"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: 'Create release PR branch'
    #   run: |
    #     NEW_RELEASE="${{ steps.update-changelog.outputs.new-release-version }}"
    #     PR_BRANCH="autorelease/$NEW_RELEASE"

    #     git config --global user.name releasebot
    #     git config --global user.email "releasebot <actions@github.com>"

    #     git checkout -b $PR_BRANCH
    #     git add .
    #     git commit -a -m "chore: Update changelog for release $NEW_RELEASE"
    #     git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git

    # - name: 'Commit changelog'
    #   uses: stefanzweifel/git-auto-commit-action@master
    #   with:
    #     commit_message: 'chore: Update changelog for release ${{ steps.update-changelog.outputs.new-release-version }}'
    #     branch: 'autorelease/${{ steps.update-changelog.outputs.new-release-version }}'
    #     create-branch: true
    #     commit_options: '--no-verify'
    #     commit_user_name: releasebot
    #     commit_user_email: actions@github.com
    #     skip_fetch: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'chore: Update changelog for release ${{ steps.update-changelog.outputs.new-release-version }}'
        committer: 'releasebot <noreply@github.com>'
        branch: 'autorelease/${{ steps.update-changelog.outputs.new-release-version }}'
        title: '[autorelease] Prepare release ${{ steps.update-changelog.outputs.new-release-version }}'
        body: >
          **This PR was created automatically by the releasebot**

          **Approving this PR will trigger the actual release**

          The changes in this PR prepare for release ${{ steps.update-changelog.outputs.new-release-version }}. They
          include:
          - Update the changelog for the latest release
        labels: autorelease
