on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        type: string
        required: true


name: '[autorelease] Release published'

jobs:
  update-ref:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get release version
      id: get-release-version
      run: |
        function semverParse() {
            local RE='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
            MAJOR=`echo $1 | sed -e "s#$RE#\1#"`
            MINOR=`echo $1 | sed -e "s#$RE#\2#"`
            PATCH=`echo $1 | sed -e "s#$RE#\3#"`
            SPECIAL=`echo $1 | sed -e "s#$RE#\4#"`
        }

        VERSION="${{ github.event.release.tag_name }}"
        if [[ ! $VERSION ]]; then
          VERSION="${{ github.event.inputs.release-version }}"
        fi

        echo "VERSION=$VERSION"
        
        RE='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
        MAJOR=`echo $VERSION | sed -e "s#$RE#\1#"`
        MINOR=`echo $VERSION | sed -e "s#$RE#\2#"`
        PATCH=`echo $VERSION | sed -e "s#$RE#\3#"`
        SPECIAL=`echo $VERSION | sed -e "s#$RE#\4#"`

        echo "MAJOR = $MAJOR"
        if [[ "$SPECIAL" ]]; then
          echo "SPECIAL present: $SPECIAL"
        else
          echo "No SPECIAL"
        fi
