on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        type: string
        required: true


name: '[autorelease] Release published'

jobs:
  update-ref:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

