on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        type: string
        required: true


name: '[autorelease] Release published'

jobs:
  update-ref:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get release version
      id: get-release-version
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        if [[ ! $VERSION ]]; then
          VERSION="${{ github.event.inputs.release-version }}"
        fi

        echo "VERSION=$VERSION"
        
        RE='^[vV]?([0-9]+)[.]([0-9]+)[.]([0-9]+)(-[0-9A-Za-z.+-]*)?'
        if [[ $VERSION =~ $RE ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          PATCH="${BASH_REMATCH[3]}"
          SPECIAL="${BASH_REMATCH[4]}"
        else
          echo "::error::Version '$VERSION' is not in a valid format" && exit 1
        fi

        echo "MAJOR = $MAJOR"
        if [[ "$SPECIAL" ]]; then
          echo "SPECIAL present: $SPECIAL"
        else
          echo "No SPECIAL"
        fi
